### ISSUE TITLE
png 파일 요청시 죽는 문제..?

### ISSUE THREAD

**Issue by maze888** [jay94ks/libnhttp#4]
우분투에서 apache 웹서버와 비교해보기위해 서로 같은 파일들을 세팅했는데요.
index.html, favicon.ico, ubuntu-logo.png 파일을 가져왔고, apache 기본 파일에서 가져왔습니다.
클라이언트가 png 파일 요청시 죽는것 같아요.

테스트 환경
<pre>
[maze@devcube 19:26:48 nhttpd]$ uname -a
Linux devcube 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[maze@devcube 19:26:49 nhttpd]$ cat /etc/issue
Ubuntu 21.04 \n \l

[maze@devcube 19:26:53 nhttpd]$ 
</pre>

죽는 증상
<pre>
[maze@devcube 19:21:14 nhttpd]$ ll
total 18528
drwxrwxr-x 3 maze maze     4096 May 26 19:21 .
drwxrwxr-x 8 maze maze     4096 May 26 12:46 ..
-rw------- 1 maze maze 17522688 May 26 19:02 core
-r--r--r-- 1 maze maze      785 May 26 19:02 favicon.ico
-rwxrwxr-x 1 maze maze   248072 May 26 19:00 httpd
drwxrwxr-x 2 maze maze     4096 May 26 11:16 icons
-rw-rw-r-- 1 maze maze    10918 May 26 19:02 index.html
-rw-rw-r-- 1 maze maze      361 May 26 19:01 index.html.bak
-rwxrwxr-x 1 maze maze   761184 May 26 18:59 libnhttp.so
-rw-rw-r-- 1 maze maze     3120 May 26 19:00 main.cpp
-rw-rw-r-- 1 maze maze   379296 May 26 19:00 main.o
-rw-rw-r-- 1 maze maze      115 May 26 18:57 Makefile
-rw-rw-r-- 1 maze maze     8707 May 26 12:46 nhttpd.vcxproj
-rw-rw-r-- 1 maze maze      207 May 26 12:46 nhttpd.vcxproj.filters
[maze@devcube 19:21:15 nhttpd]$ 
[maze@devcube 19:21:15 nhttpd]$ ./httpd 
Segmentation fault (core dumped)
[maze@devcube 19:21:22 nhttpd]$ ll icons/
total 12
drwxrwxr-x 2 maze maze 4096 May 26 11:16 .
drwxrwxr-x 3 maze maze 4096 May 26 19:21 ..
-rw-r--r-- 1 maze maze 3338 May 26 09:43 ubuntu-logo.png
[maze@devcube 19:21:44 nhttpd]$ mv icons/ icons_Bak
[maze@devcube 19:21:50 nhttpd]$ ./httpd 
</pre>

core 내용
<pre>
(gdb) where full
#0  __memchr_avx2 () at ../sysdeps/x86_64/multiarch/memchr-avx2.S:177
No locals.
#1  0x00007f4def1fabbb in nhttp::http_date::try_parse(nhttp::http_date&, char const*, long, bool) () from ./libnhttp.so
No symbol table info available.
#2  0x00007f4def22b3b0 in nhttp::server::http_vfile::on_handle(std::shared_ptr<nhttp::server::http_request>&, std::shared_ptr<nhttp::server::http_response>&, std::shared_ptr<nhttp::stream> const&, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from ./libnhttp.so
No symbol table info available.
#3  0x00007f4def231f04 in nhttp::server::http_overlay::on_handle(std::shared_ptr<nhttp::server::http_context>) () from ./libnhttp.so
No symbol table info available.
#4  0x00007f4def20436f in nhttp::server::http_listener::on_raw_context(std::shared_ptr<nhttp::server::http_raw_context> const&, bool)::{lambda()#1}::operator()() const () from ./libnhttp.so
No symbol table info available.
#5  0x00007f4def2051b1 in nhttp::_::future_task<void, nhttp::server::http_listener::on_raw_context(std::shared_ptr<nhttp::server::http_raw_context> const&, bool)::{lambda()#1}>::on_run() () from ./libnhttp.so
No symbol table info available.
#6  0x00007f4def1f40b9 in nhttp::asyncs::task::run() () from ./libnhttp.so
No symbol table info available.
#7  0x00007f4def1f33f9 in nhttp::asyncs::context::on_each_thread() () from ./libnhttp.so
No symbol table info available.
#8  0x00007f4def084694 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#9  0x00007f4deed8a450 in start_thread (arg=0x7f4deec2d640) at pthread_create.c:473
        ret = <optimized out>
        pd = 0x7f4deec2d640
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139972694955584, -7466471061006863673, 140721794207134, 140721794207135, 0, 139972694955584, 7420271530731614919, 7420271443610677959}, mask_was_saved = 0}}, 
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#10 0x00007f4deeebad53 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb) 
</pre>
icons 디렉토리 옮겨주면 죽지는 않습니다. (이미지는 빠져서 표현됨)

**Comment by jay94ks** [comment]
스택 트레이스 결과를 보면, HTTP-Date 헤더 파싱 할 때 죽은 것으로 보입니다.
1.1 버전에서 개선하도록 하겠습니다.

**Comment by jay94ks** [comment]
오래전에 개선을 이야기 드렸지만, 직장생활을 하며 바빠서 대응을 하지 못했습니다. Claude code를 이용하여 rewrite를 진행하면서 해결되었습니다.
